version: "3.8"

services:
  pushgateway:
    image: prom/pushgateway:v1.11.3
    container_name: vasin-sa-netology-pushgateway
    ports:
      - 9091:9091
    restart: unless-stopped
    networks:
      - docker2-hw-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9091/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 3

  alertmanager:
    image: prom/alertmanager:v0.34.0
    container_name: vasin-sa-netology-alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    restart: unless-stopped
    networks:
      - docker2-hw-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9093/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 3

  prometheus:
    image: prom/prometheus:v3.14.0
    container_name: vasin-sa-netology-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/first_rules.yml:/etc/prometheus/first_rules.yml
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - docker2-hw-network
    depends_on:
      alertmanager:
        condition: service_healthy
      pushgateway:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 3

  grafana:
    image: grafana/grafana:13.2.0
    container_name: vasin-sa-netology-grafana
    ports:
      - 80:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    environment:
      - GR_PATH_CONFIG=/etc/grafana/grafana.ini
    restart: unless-stopped
    networks:
      - docker2-hw-network
    depends_on:
      prometheus:
        condition: service_healthy

volumes:
  alertmanager_data:
  prometheus_data:
  grafana_data:

networks:
  docker2-hw-network:
    driver: bridge
    name: vasin-sa-my-netology-hw
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16